runnerConfig:
  - cpu: 2.0
    maxRunners: 150
    memory: 3840Mi
    minRunners: 0
    nodeType: compute-amd64
    runnerLabel: linux.large
    containerMode: dind-rootless
    workingDiskSpace: 150Gi
  - cpu: 8.0
    maxRunners: 300
    memory: 16128Mi
    minRunners: 0
    nodeType: compute-amd64
    runnerLabel: linux.2xlarge
    containerMode: dind-rootless
    workingDiskSpace: 150Gi
  - cpu: 16.0
    maxRunners: 100
    memory: 16Gi
    minRunners: 0
    nodeType: compute-amd64-amp
    runnerLabel: linux.16xl.spr
    containerMode: dind-rootless
    workingDiskSpace: 200Gi
  - cpu: 24.0
    maxRunners: 100
    memory: 45Gi
    minRunners: 0
    nodeType: compute-amd64-amp-metal
    runnerLabel: linux.24xl.spr-metal
    containerMode: dind-rootless
    workingDiskSpace: 200Gi
  - cpu: 8.0
    maxRunners: 300
    memory: 16128Mi
    minRunners: 0
    nodeType: compute-amd64-avx512
    runnerLabel: linux.2xlarge.avx512
    containerMode: dind-rootless
    workingDiskSpace: 150Gi
  - cpu: 16.0
    maxRunners: 150
    memory: 64Gi
    minRunners: 0
    nodeType: compute-amd64-nvidia-a10g
    nvidiaGpus: 1
    runnerLabel: linux.4xlarge.nvidiaa10g
    containerMode: dind-rootless
    workingDiskSpace: 150Gi
  - cpu: 48.0
    maxRunners: 150
    memory: 192Gi
    minRunners: 0
    nodeType: compute-amd64-nvidia-a10g
    nvidiaGpus: 1
    runnerLabel: linux.12xlarge.nvidiaa10g
    containerMode: dind-rootless
    workingDiskSpace: 150Gi
  - cpu: 16.0
    maxRunners: 150
    memory: 122Gi
    minRunners: 0
    nodeType: compute-amd64-nvidia-m60
    nvidiaGpus: 1
    runnerLabel: linux.4xlarge.nvidiam60
    containerMode: dind-rootless
    workingDiskSpace: 150Gi
  - cpu: 32.0
    maxRunners: 150
    memory: 244Gi
    minRunners: 0
    nodeType: compute-amd64-nvidia-m60
    nvidiaGpus: 1
    runnerLabel: linux.8xlarge.nvidiam60
    containerMode: dind-rootless
    workingDiskSpace: 150Gi
  - cpu: 8.0
    maxRunners: 150
    memory: 16Gi
    minRunners: 0
    nodeType: compute-amd64-nvidia-v100
    nvidiaGpus: 1
    runnerLabel: linux.2xlarge.nvidiav100
    containerMode: dind-rootless
    workingDiskSpace: 150Gi
