# scale-config.yml:
#   Powers what instance types are available for GHA auto-scaled
#   runners. Runners listed here will be available as self hosted
#   runners, configuration is directly pulled from the main branch.
#
# NOTE (Apr, 5, 2021): Linux runners are currently all an amazonlinux2
#
# NOTE (Jan 5, 2021): Linux runners are all non-ephemeral to reduce the amount of CreateInstaces calls
#                     to avoid RequestLimitExceeded issues
#
# TODO: Add some documentation on how the auto-scaling works
#
# NOTE: Default values,
#
# runner_types:
#   runner_label:
#     instance_type: m4.large
#     os: linux
#     max_available: 20
#     disk_size: 50
#     is_ephemeral: true

runner_types:
  linux.12xlarge:
    disk_size: 150
    instance_type: c5.12xlarge
    is_ephemeral: false
    max_available: 250
    os: linux
  linux.16xlarge.nvidia.gpu:
    disk_size: 150
    instance_type: g3.16xlarge
    is_ephemeral: false
    max_available: 30
    os: linux
  linux.24xlarge:
    disk_size: 150
    instance_type: c5.24xlarge
    is_ephemeral: false
    max_available: 250
    os: linux
  linux.2xlarge:
    disk_size: 150
    instance_type: c5.2xlarge
    is_ephemeral: false
    max_available: 3120
    os: linux
  linux.4xlarge:
    disk_size: 150
    instance_type: c5.4xlarge
    is_ephemeral: false
    max_available: 1000
    os: linux
  linux.4xlarge.nvidia.gpu:
    disk_size: 150
    instance_type: g3.4xlarge
    is_ephemeral: false
    max_available: 520
    os: linux
  linux.8xlarge.nvidia.gpu:
    disk_size: 150
    instance_type: g3.8xlarge
    is_ephemeral: false
    max_available: 400
    os: linux
  linux.g4.12xlarge.nvidia.gpu:
    disk_size: 150
    instance_type: g4dn.12xlarge
    is_ephemeral: false
    max_available: 30
    os: linux
  linux.p3.8xlarge.nvidia.gpu:
    instance_type: p3.8xlarge
    os: linux
    max_available: 10
    disk_size: 150
  linux.large:
    disk_size: 10
    instance_type: c5.large
    is_ephemeral: false
    os: linux
  linux.p324xlarge.nvidia.gpu:
    disk_size: 512
    instance_type: p3dn.24xlarge
    is_ephemeral: false
    max_available: 1
    os: linux
  linux.p4d24xlarge.nvidia.gpu:
    disk_size: 512
    instance_type: p4d.24xlarge
    is_ephemeral: false
    max_available: 1
    os: linux
  windows.4xlarge:
    disk_size: 256
    instance_type: c5d.4xlarge
    is_ephemeral: false
    max_available: 420
    os: windows
  windows.8xlarge.nvidia.gpu:
    disk_size: 256
    instance_type: p3.2xlarge
    is_ephemeral: false
    max_available: 150
    os: windows
