version: '3.7'

services:
  grafana:
    image: grafana/grafana:8.0.6
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - monitoring
    volumes:
      - /etc/pytorch/grafana:/var/lib/grafana
      - /etc/pytorch/grafana-provisioning/:/etc/grafana/provisioning
      - /etc/pytorch/email_template.html:/usr/share/grafana/public/emails/alert_notification.html
      - /etc/pytorch/grafana.ini:/etc/grafana/grafana.ini
      - /etc/pytorch/dashboards:/var/lib/grafana/dashboards

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.13.2
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - monitoring
    volumes:
      - "/etc/pytorch/kibana.yml:/usr/share/kibana/config/kibana.yml"

  nginx:
    image: nginx:1.21.0
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - monitoring
    volumes:
      - "/etc/pytorch/http.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/pytorch/fullchain.pem:/etc/nginx/fullchain.pem"
      - "/etc/pytorch/privkey.pem:/etc/nginx/privkey.pem"

networks:
  monitoring:
    external: false
