name: anaconda-prune

on:
  schedule:
    - cron: 45 1,13 * * *
  pull_request:
    paths:
      - .github/workflows/anaconda-prune.yml
      - .github/workflows/_prune-anaconda-packages.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  anaconda-prune-pytorch-nightly:
    name: anaconda-prune-pytorch-nightly
    uses: ./.github/workflows/_prune-anaconda-packages.yml
    with:
      packages: "pytorch torchvision torchaudio torchtext torchdata ignite torchcsprng torchserve torcharrow"
      channel: pytorch-nightly
    secrets:
     conda-pytorchbot-token: ${{ secrets.CONDA_PYTORCHBOT_TOKEN }}

  anaconda-prune-pytorch-test:
    name: anaconda-prune-pytorch-test
    uses: ./.github/workflows/_prune-anaconda-packages.yml
    needs: anaconda-prune-pytorch-nightly
    with:
      packages: "pytorch torchvision torchaudio torchtext torchdata ignite torchcsprng"
      channel: pytorch-test
    secrets:
     conda-pytorchbot-token: ${{ secrets.CONDA_PYTORCHBOT_TOKEN }}
