name: Backfill workflow jobs in Rockset

on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: torchci

permissions:
  id-token: write
  contents: read

jobs:
  backfill-rockset:
    runs-on: ubuntu-20.04
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_backfill-workflow-job
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn node scripts/backfillJobs.mjs
        env:
          ROCKSET_API_KEY: ${{ secrets.ROCKSET_API_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
