name: Backfill workflow jobs in DynamoDB and ClickHouse

on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: torchci
jobs:
  backfill-workflow-job:
    runs-on: ubuntu-24.04
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_backfill-workflow-job
          aws-region: us-east-1
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: yarn install --frozen-lockfile
      - run: yarn node scripts/backfillJobs.mjs
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLICKHOUSE_HUD_USER_URL: ${{ secrets.CLICKHOUSE_HUD_USER_URL }}
          CLICKHOUSE_HUD_USER_USERNAME: ${{ secrets.CLICKHOUSE_HUD_USER_USERNAME }}
          CLICKHOUSE_HUD_USER_PASSWORD: ${{ secrets.CLICKHOUSE_HUD_USER_PASSWORD }}
