name: Build Windows AMI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'pytorch/test-infra branch to build from. (default: main)'
        required: true
        default: 'main'
      skip_create_ami:
        description: 'Skip creating the AMI (default: false)'
        required: true
        default: false

permissions:
  id-token: write
  contents: read

env:
  PACKER_VERSION: "1.11.2"

jobs:
  build-windows-ami:
    runs-on: ubuntu-latest
    environment: packer-build-env
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: pytorch/test-infra
          ref: ${{ inputs.branch }}

      - name: Configure AWS Credentials (PyTorch Account)
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::391835788720:role/gha-packer-role

      - name: Setup Packer
        uses: hashicorp/setup-packer@76e3039aa951aa4e6efe7e6ee06bc9ceb072142d # main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Packer Build
        run: |
          cd aws/ami/windows
          packer init .
          PACKER_LOG=1 packer build -var 'skip_create_ami=${{ inputs.skip_create_ami }}' .
