name: Lintrunner CI

on:
  pull_request:
    # paths:
    #   - 'tools/lintrunner/**'
  push:
    branches:
      - main
    tags:
      - lintrunner/v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Initialize git config for testing
        run: |
          git config --global user.email "fake@email.com"
          git config --global user.name "mr fake"
      - name: Install and initialize sapling on macos
        if: matrix.os == 'macos-latest'
        run: |
          brew install sapling
          sl config --user ui.username "mr fake <fake@email.com>"
      - name: Run cargo test
        uses: nick-fields/retry@v2.8.2
        env:
          TMPDIR: ${{ runner.temp }}
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_wait_seconds: 90
          command: |
            cd tools/lintrunner
            cargo test


  linux:
    runs-on: ubuntu-latest
    # needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: messense/maturin-action@v1
      with:
        manylinux: auto
        command: build
        args: --release -o dist
        working-directory: tools/lintrunner
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: tools/lintrunner/dist

  windows:
    runs-on: windows-latest
    # needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release -o dist
        working-directory: tools/lintrunner
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: tools/lintrunner/dist

  macos:
    runs-on: macos-latest
    # needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --universal2 -o dist
        working-directory: tools/lintrunner
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: tools/lintrunner/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    # if: "startsWith(github.ref, 'refs/tags/lintrunner/v*')"
    # needs: [ macos, windows, linux, test ]
    needs: [ macos, windows, linux ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Publish to PyPI
        uses: messense/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing -- *glob*
