name: Publish Alerts
on:
  pull_request:
    paths:
      - .github/workflows/publish_alerts.yaml
      - tools/alerts/*
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:


jobs:
  update-alerts:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
           pip3 install requests requests
      - name: Check for alerts and creates issue
        run: |
          python3 tools/alerts/publish_alerts.py
        env:
          # NOTE: Should be a blank string for pull requests
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROCKSET_API_KEY: ${{ secrets.ROCKSET_API_KEY }}