name: revert printer

on:
  repository_dispatch:
  schedule:
    # At 16:39 (9:39 AM PST) on Monday
    - cron: 39 16 * * 1

jobs:
  revert_printer:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: test-infra
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: pytorch/pytorch
          path: pytorch
          fetch-depth: 0
      - id: generate-reverts-file
        run: |
          cd test-infra
          python3 -m pip install rockset==0.8.3
          file=$(python3 -m torchci.scripts.reverts)
          echo "::set-output name=revert_file::$file"
        env:
          ROCKSET_API_KEY: ${{ secrets.ROCKSET_API_KEY }}

      - name: Push file to this repository
        if: steps.generate-reverts-file.outputs.revert_file != 'None'
        uses: dmnemec/copy_file_to_another_repo_action@5f40763ccee2954067adba7fb8326e4df33bcb92
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: test-infra/${{ steps.generate-reverts-file.outputs.revert_file }}
          destination_repo: "pytorch/test-infra"
          destination_folder: "reverts"
          destination_branch: generated-stats
          user_email: "test-infra@pytorch.org"
          user_name: "PyTorch Test Infra"
          commit_message: "Updating helper for reverts"
