name: Test Build M1 Conda

on:
  pull_request:
    paths:
      - .github/actions/setup-binary-builds/action.yml
      - .github/workflows/temp_test_build.yml
      - .github/workflows/build_conda_macos.yml
      - .github/workflows/generate_binary_build_matrix.yml
      - .github/workflows/_binary_conda_upload.yml
      - tools/scripts/generate_binary_build_matrix.py
  workflow_dispatch:

jobs:
  generate-matrix:
    uses: ./.github/workflows/generate_binary_build_matrix.yml
    with:
      package-type: conda
      os: macos-arm64
      test-infra-repository: ${{ github.repository }}
      test-infra-ref: ${{ github.ref }}
  test:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: pytorch/audio
            conda-package-directory: packaging/torchaudio
            smoke-test-script: test/smoke_test/smoke_test.py
            package-name: torchaudio
          - repository: pytorch/vision
            cache-path: ""
            cache-key: ""
            conda-package-directory: packaging/torchvision
            smoke-test-script: test/smoke_test.py
            package-name: torchvision
    name: ${{ matrix.repository }}
    uses: ./.github/workflows/build_conda_macos.yml
    with:
      conda-package-directory: ${{ matrix.conda-package-directory }}
      repository: ${{ matrix.repository }}
      ref: nightly
      test-infra-repository: ${{ github.repository }}
      test-infra-ref: ${{ github.ref }}
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      smoke-test-script: ${{ matrix.smoke-test-script }}
      runner-type: macos-m1-stable
      package-name: ${{ matrix.package-name }}
      trigger-event: "${{ github.event_name }}"
      cache-path: ${{ matrix.cache-path }}
      cache-key: ${{ matrix.cache-key }}
    secrets:
      CONDA_PYTORCHBOT_TOKEN: ${{ secrets.CONDA_PYTORCHBOT_TOKEN }}
