name: Test Build Linux Conda with CUDA

on:
  pull_request:
    paths:
      - .github/actions/setup-binary-builds/action.yml
      - .github/workflows/test_build_conda_linux.yml
      - .github/workflows/build_conda_linux.yml
      - .github/workflows/generate_binary_build_matrix.yml
      - tools/scripts/generate_binary_build_matrix.py
  workflow_dispatch:

jobs:
  generate-matrix:
    uses: ./.github/workflows/generate_binary_build_matrix.yml
    with:
      package-type: conda
      os: linux
      test-infra-repository: ${{ github.repository }}
      test-infra-ref: ${{ github.ref }}
  test:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: pytorch/audio
            cache-path: /third_party/ffmpeg
            cache-key: linux-ffmpeg
            cache-miss-script: packaging/pre_build_script.sh
            pre-script: ""
            post-script: packaging/post_build_script.sh
            smoke-test-script: test/smoke_test/smoke_test.py
            conda-package-directory: packaging/torchaudio
            package-name: torchaudio
          - repository: pytorch/vision
            pre-script: ""
            post-script: ""
            smoke-test-script: test/smoke_test.py
            conda-package-directory: packaging/torchvision
            package-name: torchvision
            cache-miss-script: ""
            cache-path: ""
            cache-key: ""

    name: ${{ matrix.repository }}
    uses: ./.github/workflows/build_conda_linux.yml
    with:
      conda-package-directory: ${{ matrix.conda-package-directory }}
      repository: ${{ matrix.repository }}
      ref: nightly
      test-infra-repository: ${{ github.repository }}
      test-infra-ref: ${{ github.ref }}
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      pre-script: ${{ matrix.pre-script }}
      post-script: ${{ matrix.post-script }}
      smoke-test-script: ${{ matrix.smoke-test-script }}
      package-name: ${{ matrix.package-name }}
      trigger-event: "${{ github.event_name }}"
      cache-miss-script: ${{ matrix.cache-miss-script }}
      cache-path: ${{ matrix.cache-path }}
      cache-key: ${{ matrix.cache-key }}
    secrets:
      CONDA_PYTORCHBOT_TOKEN: ${{ secrets.CONDA_PYTORCHBOT_TOKEN }}
