name: Test Build Linux Conda without CUDA

on:
  pull_request:
    paths:
      - .github/actions/setup-binary-builds/action.yml
      - .github/workflows/test_build_conda_linux.yml
      - .github/workflows/build_conda_linux.yml
      - .github/workflows/generate_binary_build_matrix.yml
  workflow_dispatch:

jobs:
  generate-matrix:
    uses: ./.github/workflows/generate_binary_build_matrix.yml
    with:
      package-type: conda
      os: linux
      test-infra-repository: ${{ github.repository }}
      test-infra-ref: ${{ github.ref }}
      with-cuda: disable
  test:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: pytorch/text
            pre-script: ""
            post-script: ""
            conda-package-directory: packaging/torchtext
    name: ${{ matrix.repository }}
    uses: ./.github/workflows/build_conda_linux.yml
    with:
      conda-package-directory: ${{ matrix.conda-package-directory }}
      repository: ${{ matrix.repository }}
      ref: nightly
      test-infra-repository: ${{ github.repository }}
      test-infra-ref: ${{ github.ref }}
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      pre-script: ${{ matrix.pre-script }}
      post-script: ${{ matrix.post-script }}
      package-name: ${{ matrix.package-name }}
      trigger-event: "${{ github.event_name }}"
