name: Test Build M1 Conda

on:
  pull_request:
    paths:
      - .github/actions/setup-binary-builds/action.yml
      - .github/workflows/test_build_conda_m1.yml
      - .github/workflows/build_conda_macos.yml
      - .github/workflows/generate_binary_build_matrix.yml
      - tools/scripts/generate_binary_build_matrix.py
  workflow_dispatch:

jobs:
  generate-matrix:
    uses: ./.github/workflows/generate_binary_build_matrix.yml
    with:
      package-type: conda
      os: macos-arm64
      test-infra-repository: ${{ github.repository }}
      test-infra-ref: ${{ github.ref }}
  test:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: pytorch/audio
            pre-script: packaging/pre_build_script.sh
            post-script: packaging/post_build_script.sh
            conda-package-directory: packaging/torchaudio
            smoke-test-script: test/smoke_test/smoke_test.py
            package-name: torchaudio
          - repository: pytorch/audio
            cache-path: /third_party/ffmpeg
            cache-key: macos-m1-ffmpeg
            pre-script: packaging/pre_build_script.sh
            post-script: packaging/post_build_script.sh
            conda-package-directory: packaging/torchaudio
            smoke-test-script: test/smoke_test/smoke_test.py
            package-name: torchaudio
          - repository: pytorch/vision
            pre-script: ""
            post-script: ""
            conda-package-directory: packaging/torchvision
            smoke-test-script: test/smoke_test.py
            package-name: torchvision
          - repository: pytorch/text
            pre-script: packaging/install_torchdata.sh
            post-script: ""
            conda-package-directory: packaging/torchtext
            smoke-test-script: test/smoke_tests/smoke_tests.py
            package-name: torchtext
    name: ${{ matrix.repository }}
    uses: ./.github/workflows/build_conda_macos.yml
    with:
      conda-package-directory: ${{ matrix.conda-package-directory }}
      repository: ${{ matrix.repository }}
      ref: nightly
      test-infra-repository: ${{ github.repository }}
      test-infra-ref: ${{ github.ref }}
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      pre-script: ${{ matrix.pre-script }}
      post-script: ${{ matrix.post-script }}
      smoke-test-script: ${{ matrix.smoke-test-script }}
      runner-type: macos-m1-12
      package-name: ${{ matrix.package-name }}
      trigger-event: "${{ github.event_name }}"
    secrets:
      CONDA_PYTORCHBOT_TOKEN: ${{ secrets.CONDA_PYTORCHBOT_TOKEN }}
