name: Test Build MacOS Wheels

on:
  pull_request:
    paths:
      - .github/actions/setup-binary-builds/action.yml
      - .github/workflows/test_build_wheels_macos.yml
      - .github/workflows/build_wheels_macos.yml
      - .github/workflows/generate_binary_build_matrix.yml
      - tools/scripts/generate_binary_build_matrix.py
  workflow_dispatch:

jobs:
  generate-matrix:
    uses: ./.github/workflows/generate_binary_build_matrix.yml
    with:
      package-type: wheel
      os: macos
      test-infra-repository: ${{ github.repository }}
      test-infra-ref: ${{ github.ref }}
  test:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: pytorch/audio
            cache-path: /third_party/ffmpeg
            cache-key: macos-ffmpeg
            pre-script: packaging/pre_build_script.sh
            post-script: packaging/post_build_script.sh
            conda-package-directory: packaging/torchaudio
            smoke-test-script: test/smoke_test/smoke_test.py
            package-name: torchaudio
          - repository: pytorch/vision
            pre-script: packaging/pre_build_script.sh
            post-script: packaging/pre_build_script.sh
            smoke-test-script: test/smoke_test.py
            package-name: torchvision
          - repository: pytorch/text
            pre-script: packaging/install_torchdata.sh
            post-script: ""
            smoke-test-script: test/smoke_tests/smoke_tests.py
            package-name: torchtext
    uses: ./.github/workflows/build_wheels_macos.yml
    name: ${{ matrix.repository }}
    with:
      repository: ${{ matrix.repository }}
      ref: nightly
      test-infra-repository: ${{ github.repository }}
      test-infra-ref: ${{ github.ref }}
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      pre-script: ${{ matrix.pre-script }}
      post-script: ${{ matrix.post-script }}
      smoke-test-script: ${{ matrix.smoke-test-script }}
      runner-type: macos-12
      package-name: ${{ matrix.package-name }}
      trigger-event: "${{ github.event_name }}"
