name: Update disabled tests

on:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:

jobs:
  update-disabled-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate new disabled test json
        run: |
          .github/scripts/update_disabled_tests.py
      - name: Print file
        run: |
          cat disabled-tests.json
          cat disabled-tests-condensed.json
      - name: Push file to test-infra repository
        uses: dmnemec/copy_file_to_another_repo_action@eebb594efdf52bc12e1b461988d7254322dac131
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: "disabled-tests.json"
          destination_repo: "pytorch/test-infra"
          destination_folder: "stats"
          destination_branch: generated-stats
          user_email: "test-infra@pytorch.org"
          user_name: "Pytorch Test Infra"
          commit_message: "Updating disabled tests stats"
      - name: Push file to test-infra repository
        uses: dmnemec/copy_file_to_another_repo_action@eebb594efdf52bc12e1b461988d7254322dac131
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: "disabled-tests-condensed.json"
          destination_repo: "pytorch/test-infra"
          destination_folder: "stats"
          destination_branch: generated-stats
          user_email: "test-infra@pytorch.org"
          user_name: "Pytorch Test Infra"
          commit_message: "Updating condensed disabled tests stats"
