name: Update slow tests

on:
  schedule:
    # Every day at 5:05pm EDT
    - cron: "5 21 * * *"
  # Have the ability to trigger this job manually
  workflow_dispatch:
  pull_request:

defaults:
  run:
    working-directory: torchci
jobs:
  update-slow-stats:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn --silent node scripts/updateSlowTests.mjs > slow-tests-by-job.json
        env:
          ROCKSET_API_KEY: ${{ secrets.ROCKSET_API_KEY }}
      - name: Push file to this repository
        uses: dmnemec/copy_file_to_another_repo_action@5f40763ccee2954067adba7fb8326e4df33bcb92
        env:
           API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: 'torchci/slow-tests-by-job.json'
          destination_repo: 'pytorch/test-infra'
          destination_folder: 'stats'
          destination_branch: generated-stats
          user_email: 'test-infra@pytorch.org'
          user_name: 'PyTorch Test Infra'
          commit_message: 'Updating slow tests stats'
      - name: Upload file to s3
        run: |
          python3 -mpip install awscli==1.27.69
          aws s3 cp "slow-tests-by-job.json" s3://ossci-metrics/slow-tests-by-job.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
