name: Update queue times dataset

on:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"

defaults:
  run:
    working-directory: torchci
jobs:
  update-queue-rockset:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - name: configure aws credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_update_queue_times
          aws-region: us-east-1
      - run: yarn node scripts/updateQueueTimes.mjs
        env:
          OUR_AWS_ACCESS_KEY_ID: ${{ steps.aws_creds.outputs.aws-access-key-id }}
          OUR_AWS_SECRET_ACCESS_KEY: ${{ steps.aws_creds.outputs.aws-secret-access-key }}
          ROCKSET_API_KEY: ${{ secrets.ROCKSET_API_KEY }}
