name: Update Dr. CI comments

on:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"
  # Have the ability to trigger this job manually through the API (temporary)
  workflow_dispatch:  

jobs:
  update-drci-comments:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve rockset query results and update Dr. CI comments
        run: |
          curl --request POST \
          --url 'https://www.torch-ci.com/api/drci/drci' \
          --header 'Authorization: ${{ secrets.GITHUB_TOKEN }}'
        # not sure what authorization tokens i need
