name: Test File Report Generator

on:
  schedule:
    # Run every day at 2am UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  file-report:
    runs-on: linux.2xlarge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -mpip install -r tools/torchci/requirements.txt
          cd tools/torchci && python3 -mpip install -e .

      - name: Run file report generator
        env:
          CLICKHOUSE_ENDPOINT: ${{ secrets.CLICKHOUSE_HUD_USER_URL }}
          CLICKHOUSE_USERNAME: ${{ secrets.CLICKHOUSE_HUD_USER_USERNAME }}
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_HUD_USER_PASSWORD }}
        run: |
          YESTERDAY=$(date -u -d "yesterday" +%Y-%m-%d)
          python3 tools/torchci/test_insights/file_report_generator.py \
            --add-dates "$YESTERDAY"
