name: Update Dr. CI comments

on:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:

jobs:
  update-drci-comments:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        repo: [
          ao,
          audio,
          data,
          executorch,
          pytorch,
          rl,
          text,
          torchchat,
          torchtune,
          tutorials,
          vision,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve rockset query results and update Dr. CI comments
        run: |
          curl --request POST \
          --url 'https://www.torch-ci.com/api/drci/drci' \
          --header 'Authorization: ${{ secrets.DRCI_BOT_KEY }}' \
          --data 'repo=${{ matrix.repo }}' \
          --silent --output /dev/null --show-error --fail
