name: Upload tutorials stat

on:
  schedule:
  # Run this once per day.
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  get-tutorials-stats:
    if: ${{ github.repository == 'pytorch/test-infra' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure aws credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_upload-tutorials-stats
          aws-region: us-east-1

      - name: Checkout the tutorials repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'pytorch/tutorials'
          path: './tutorials'
          fetch-depth: 0

      - name: Checkout the pytorch repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'pytorch/pytorch'
          path: './pytorch'
          fetch-depth: 0

      - name: Checkout the test-infra repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: test-infra

      - name: Install dependencies
        run: |
          python3 -m pip install boto3==1.26.69

      - name: Run the script
        run: |
          set -x
          python3 test-infra/.github/scripts/get_tutorials_stats.py
